//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile_Web.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int product_id { get; set; }
        public string username { get; set; }
        public string product_name { get; set; }
        public string product_type { get; set; }
        public int price { get; set; }
        public string payment_method { get; set; }
        public string image { get; set; }
    
        public virtual User User { get; set; }
    }
}
